<?php
/*
 * QualityCallTesterLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 12/07/2015
 */

namespace QualityCallTesterLib;

class Configuration {
    //The base Uri for API calls
    public static $BASEURI = 'https://api.qualitycalltester.dev/app_dev.php';

    //API Authentication Token
    //TODO: Replace the $xAPITOKEN with an appropriate value
    public static $xAPITOKEN = 'TODO: Replace';

}
